### ISSUE TITLE
Add Json Bodies for Errors

### ISSUE THREAD

**Issue by Drxckzyz** [FerrisChat/Server#2]
**Is your feature request related to a problem? Please describe.**
Sending the error code alone means that Api library developers have to either just use the status text as the error or write some function to determine what caused the error which is additional work which is not needed

**Describe the solution you'd like**
I would like for most (if possible all) Errors to return a json (or just a response) to make it easier on Api library developers.

**Describe alternatives you've considered**
Send it as Text

**Additional context**
Nope.

This is more of a can i create a pr to implement this, i know i need to add the json types to the [Common Repo](https://github.com/FerrisChat/Common)

**Comment by hydrostaticcog** [comment]
Hello,

Yes, you may create a PR to implement that, though please make all your changes to the Common Repo first (and PR there), since the compiler will rely on the GitHub repo to get the types.

**Comment by Drxckzyz** [comment]
Ok Noted

**Comment by Drxckzyz** [comment]
Just some testing and the pr will be ready

**Comment by tazz4843** [comment]
Closed by #4
