### ISSUE TITLE
`GET /users` does not include channels or members

### ISSUE THREAD

**Issue by jay3332** [FerrisChat/Server#40]
`guilds.N.channels` is always `null` regardless of how many channels are in each guild
`guilds.N.members` is also always `null`, make sure to also include `.members.N.user` too

Workaround is to make an additional API request every time you need the channels of a guild

**Comment by tazz4843** [comment]
hmm

this should be relatively easy to implement, it most likely just needs some sort of second query returning channels

**Comment by hydrostaticcog** [comment]
Discovered on production

**Comment by hydrostaticcog** [comment]
Partially patched by #56.
`GET /users/id` does return channels, just not user

**Comment by Cryptex-github** [comment]
I shall fix this

**Comment by tazz4843** [comment]
Actually closed in #62
