### ISSUE TITLE
[500]: `DELETE` Guilds returns an Internal Error

### ISSUE THREAD

**Issue by Drxckzyz** [FerrisChat/Server#42]
### API Endpoint

/guilds/{Id}

### What's the JSON response you got?

```json
{"reason":"DB returned a error: error returned from database: update or delete on table \"guilds\" violates foreign key constraint \"members_guild_id_fkey\" on table \"members\""}
```

### Request info

The headers contained the following:
- Authorization
- User-Agent: `FerrisLib (https://github.com/Drxckzyz/Ferris-lib, 0.0.3)`

This request had no Body

### More Info

The Javascript API Wrapper [Ferris-Lib](https://github.com/FerrisChat/Ferris-lib) was used.
You may view the used code [here](https://github.com/FerrisChat/Ferris-lib/blob/main/test/test.js)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by tazz4843** [comment]
closed in 815e123e85f7dd37e2f472fb1edaf891f3faa9df
