### ISSUE TITLE
Join guild multiple times

### ISSUE THREAD

**Issue by hydrostaticcog** [FerrisChat/Server#58]
**Describe the bug**
The `POST /invite/{code}` endpoint allows you to join a guild multiple times.

**To Reproduce**
1. Join a guild
2. On GET GUILD, you are returned once
3. Join the same guild again
4. On GET GUILD, you are returned twice

**Expected behavior**
Only returned once/only added to DB once

**Screenshots**
no screenshot, just excerpt from DB
```
1089570323800355773090440413184 | 1088707735803565215231395758080
1088821734892678789830361481216 | 1088707735803565215231395758080
1088821734892678789830361481216 | 1088707735803565215231395758080
1088821734892678789830361481216 | 1088707735803565215231395758080
1088821734892678789830361481216 | 1088707735803565215231395758080
1088821734892678789830361481216 | 1088707735803565215231395758080
1088821734892678789830361481216 | 1088707735803565215231395758080
1088821734892678789830361481216 | 1088707735803565215231395758080
1088821734892678789830361481216 | 1088707735803565215231395758080
1088821734892678789830361481216 | 1088707735803565215231395758080
1088821734892678789830361481216 | 1088707735803565215231395758080
1088821734892678789830361481216 | 1088707735803565215231395758080
1088821734892678789830361481216 | 1088707735803565215231395758080

```

**Desktop (please complete the following information):**
 - OS: endeavourOS
 - Version: 5.14.12
 - Rust Version: 1.58

**Additional context**
Used raw API requests, WebClient, and DB access to validate.

**Comment by tazz4843** [comment]
fixed in f49c6c54db5f30d3165bcbf94b764feb3817c1f3
