### ISSUE TITLE
Guilds always empty

### ISSUE THREAD

**Issue by alf1e** [FerrisChat/Server#73]
**Describe the bug**
Im in guilds in the DB but not in FerrisWheel

**To Reproduce**
```py
client = ferris.Client()

@client.listen()
async def on_ready():
    print("Terris is ready")
    g = await client.create_guild(name="Test Guild")
    c = await g.create_channel(name="Test Channel")

    print(client.user.guilds)

client.run(email=email, password=password)
```

**Expected behavior**
Print guilds to console

**Screenshots**
N/A

**Library version**
0.0.b1

**Python version**
3.9

**OS Info**
ubuntu

**Additional context**
DB says Im in guilds.

**Comment by hydrostaticcog** [comment]
Fixed by #74
