### ISSUE TITLE
Backend Optimization

### ISSUE THREAD

**Issue by hydrostaticcog** [FerrisChat/Server#77]
The backend needs some optimization. With the merging of #74, the REST API has been sped up, but the WebSocket now lacks speed/is unable to handle a more than reasonable amount of requests.

- [X] WebServer rewrite
- [ ] #83
- [ ] JSON lib

@FerrisChat/maintainers feel free to check/add boxes

**Comment by tazz4843** [comment]
What does "JSON lib" mean in this context? Do you mean the library used for processing events in Redis behind-the-scenes?

**Comment by hydrostaticcog** [comment]
Weren't you testing using a new crate to serialize/deserialize json, instead of serde?

**Comment by tazz4843** [comment]
That was implemented long ago, and just has a few issues preventing 100% implementation which can't easily be worked out.
