### ISSUE TITLE
Permissions database representation

### ISSUE THREAD

**Issue by tazz4843** [FerrisChat/Server#81]
Permissions are not a simple boolean, so we can't represent them with just bitflags easily. We need another way of representing them.

**Comment by hydrostaticcog** [comment]
Can we not store them as bits from bitflags?

**Comment by tazz4843** [comment]
They aren't just booleans so a single bit couldn't represent them: we'd need two bits per permission node to represent them accurately.

**Comment by hydrostaticcog** [comment]
Right because we have neutral.

**Comment by hydrostaticcog** [comment]
Can we implement some kind of tri-bool?

**Comment by tazz4843** [comment]
Tribools are what is currently in use, but they require two bits of storage space.

**Comment by hydrostaticcog** [comment]
I mean, we don't want a column per permission.
